### ISSUE TITLE
Post 的 Title 需不需要存在

### ISSUE THREAD

**Issue by yuchunc** [elixirtw/elixir_tw#14]
我覺得 Post 因該不用 `validate_required(:title)`
一來是因為已經有 slug 來判斷是哪篇文章，另外或許使用者可以比較自由的選擇要不要使用 Title
沒有的就只是 SEO 對他們比較不利 + 看起來比較醜~ 
@taiansu

**Comment by taiansu** [comment]
@yuchunc 可是 post index 是用 post.title 來列清單的，如果沒有 Title 就會有標題為空白的項目，讀讀者在點進去之前不知道這篇在講什麼。:slug 也不太適合拿來當列表的項目欄位。最後我會覺得想不到有什麼不設 title 的適用情況。

**Comment by yuchunc** [comment]
是沒錯啦... 那先這樣吧
我本來想說可以順便拿來當 Comments用，不過突然想到昨天的 ecto talk 可以直接定義 Comment scheama 吃 posts 就可以了
or just have another comments table
