### ISSUE TITLE
Proper configuration for semantic-ui

### ISSUE THREAD

**Issue by otaq** [elixirtw/elixir_tw#5]
Hi @yuchunc, I'm new to Elixir Taiwan.

I saw elixirtw/elixir_tw@9529e6fdb7d560cdd924c01718e033ddea82b7cc that whole semantic-ui source code was committed. It's quite huge for a git commit and icon fonts and css flag sprites are not working.

IMHO we shouldn't commit dependency's source code into repo, since we don't want to maintain or customize it or do we? Actually if we want to customize a dependency, we should fork it as our customized dependency repo, not commit it into project repo. Follow this idea, in this case, the only thing we do to semantic-ui is manage its version.

Here is my minimal configuration for semantic-ui otaq/elixir_tw@813a8c638fd40deb074d2afc43691cfaf26e7165 icon fonts and css flag sprites are working.

I can create a pull request with these [commits](https://github.com/otaq/elixir_tw/commits/proper-config-for-semantic-ui) if you like or just close this issue. Although I wish to remove semantic-ui source code entirely from git history, use `git rebase -i` and `git push -f` just for this case but I don't have permission. Any ideas?

**Comment by taiansu** [comment]
@otaq @yuchunc I'll vote for removing the static code from the history.

**Comment by otaq** [comment]
It's done, rebase if you like.
https://github.com/otaq/elixir_tw/commits/cleanup-semantic-ui-source-code

**Comment by yuchunc** [comment]
Hey @otaq, if you want to be a contributor, you are more then welcome! Just let me know. =)

I am going to study up on how to do this rebase properly tomorrow, or maybe you can force push with your local branch once you get the permission?

**Comment by yuchunc** [comment]
@otaq I send you the confirmation for member of elixir-tw, enjoy =)

**Comment by otaq** [comment]
Thank you @yuchunc and your kindness. I'm here to help because I wish the community can grows.

There are many way to do this. In my opinion the fastest way is:

- Add `git@github.com:otaq/elixir_tw.git` to git remote
  - `git remote add otaq git@github.com:otaq/elixir_tw.git`
- Fetch that `cleanup-semantic-ui-source-code` branch to origin(elixir_tw) 
  - `git fetch otaq cleanup-semantic-ui-source-code`
  - `git checkout cleanup-semantic-ui-source-code`
- Compare `master` and `cleanup-semantic-ui-source-code` branch
  - Make sure this guy(@otaq) didn't break things and everything work as expected
- If everything is ok
  - create a backup branch
  - `git reset --hard` to the commit before semantic-ui was added
  - `git rebase cleanup-semantic-ui-source-code`

Or you want to do it from the very beginning:

  - find every commits that contains file/folder which need to be removed or modified
  - create a backup branch
  - `git rebase -i` from the first commit where semantic-ui was added
  - apply proper config and remove static files
  - fix conflict

And if I have permission to force push, I need at least one collaborator knows what exactly have I done.

**Comment by yuchunc** [comment]
I'm by no mean familiar with open source project, this is my first! It's all learning process for me. = )
I am always prepare to watch and learn. 

I checked in your changes into a branch and push to this repo. I guess preparing for theming with semantic-ui is a bit overkill at this point.

I have created a pull request, I think there would still be some fixing, but generally it runs fine. 
NOTE to self: Write some tests. 

#6

**Comment by otaq** [comment]
Yeah, we always learning. :D

I leave those need to be fixed as it-is, so it won't off topic.

Here are files/folders that changes when I'm doing rebase:

```
# Command to compare two branches, using grep because it is too large. I use GUI tools tho.
$ git diff master..cleanup-semantic-ui-source-code | grep 'diff --git'
```

- /brunch-config.js `modified`
- /package.json `modified`
- /semantic `removed`
- /web/static/vendor `removed`
- /web/templates/layout/app.html.eex `modified`

And I leave commit message untouched. There are some commits are missing because it only contains file/folder need to be removed or some changes will never happen after rebase.

I got nothing to do with #6. it can't be merged because it is a history rewrite, it can only be force pushed to `master` to change the history.

If you are ok with #6 , I will do the steps below:

```
$ git checkout master
$ git reset --hard 4151ad01ac0a12e202e2c8380e8385f600a63da4
$ git rebase cleanup-semantic-ui-source-code
$ git push -f 
```

**Comment by taiansu** [comment]
I'm done. How about you, @yuchunc ?

**Comment by yuchunc** [comment]
我也可以! 感謝 @otaq!

不好意思 最近比較忙 + Burned out 中...
